spring:
  application:
    name: samofujera
  flyway:
    enabled: true
    locations: classpath:db/migration
  jooq:
    sql-dialect: postgres
  session:
    store-type: redis
    redis:
      namespace: samofujera:session
    timeout: 30d
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
  security:
    filter:
      order: -100
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
